### ISSUE TITLE
Carpeta especificada

### ISSUE THREAD

**Issue by BryanJT01** [Roberto-Garijo/OpusList#1]
![image](https://user-images.githubusercontent.com/77690759/140784497-d5e69d13-dc51-4ce8-b316-3357b7887e13.png)

La ruta suelta error por ser diferente al mencionada por el ejercicio, probar a cambiar la ruta a "C:\Users\xxx\AppData\Local\OpusList\data\obres.json"

![image](https://user-images.githubusercontent.com/77690759/140784997-21e9cefc-c515-48aa-97ce-4933cefb2623.png)

**Comment by Roberto-Garijo** [comment]
Commiteado la corrección del error, el path de save y load ha sido correjido
