### ISSUE TITLE
Update a register image null. 

### ISSUE THREAD

**Issue by AdrianGonzalezB** [Roberto-Garijo/OpusList#2]
`
Cuando haces Update de una obra y no insertas un Update de la imagen esta se pone a null.
`

![image](https://user-images.githubusercontent.com/77398604/141132758-d483b98c-b759-4db2-a709-4b5850f210fb.png)

**Comment by Roberto-Garijo** [comment]
La imagen ya se pone correctamente y se guarda en el appdata
