### ISSUE TITLE
Guardado de la imagen de una nueva obra al fichero destino

### ISSUE THREAD

**Issue by sergicladeraben** [Roberto-Garijo/OpusList#3]
Al insertar una nueva obra se muestra en el JList pero no se guarda en la carpeta de imagenes que hemos establecido como destino.
- Al darle al boton insert del InsertDialog no especificas donde se tiene que guardar la imagen asignada a esa nueva obra.
![image](https://user-images.githubusercontent.com/77398698/141135324-95527f6f-9ba8-47e2-99c3-5c8c4565ae80.png)

Una vez añadido el path destino del Insert, se tiene que cambiar el metodo lstOpusValueChanged de la clase OpusListMainForm para que el path sea el correcto.
![image](https://user-images.githubusercontent.com/77398698/141135720-0d35eac4-2a5b-4fa5-9af5-b66308b70c56.png)

**Comment by Roberto-Garijo** [comment]
Acabo de hacer un commit con el programa arreglado, ya deberia de ir bien
