### ISSUE TITLE
Las imagenes no se guardan en el directorio

### ISSUE THREAD

**Issue by BryanJT01** [Roberto-Garijo/OpusList#4]
![image](https://user-images.githubusercontent.com/77690759/141132379-169eca64-de7c-47bc-bfa7-71c7e8f9560c.png)

El error se da en el momento de insertar, no se guarda la imagen

En el metodo lstOpusValueChanged del main debes cambiar la ruta  de guardado de imagen
![image](https://user-images.githubusercontent.com/77690759/141134116-f6894de9-6042-48d9-b5d1-8c735dfa8723.png)

En el boton insert del insertDialog debes crear el try/catch para guardar la imagen en esa carpeta
![image](https://user-images.githubusercontent.com/77690759/141134225-1589d0ac-a120-49f6-a0ab-06ea56cdaf53.png)

**Comment by Roberto-Garijo** [comment]
Correjido error, las imagenes ya se guardan en el directorio adecuado
