### ISSUE TITLE
Al insertar un usuario sin imagen, no se le establece la imagen por defecto

### ISSUE THREAD

**Issue by sergicladeraben** [Roberto-Garijo/OpusList#5]
Cuando insertamos un nuevo usuario pero a este no le escojemos una imagen, no se establece la imagen default.jpg.
Este tampoco se introduce en la carpeta destino C:\XXX\XXX\AppData\Local\OpusList\images.

**Comment by Roberto-Garijo** [comment]
Correjido error, ahora ya se puede añadir una obra sin imagen
